# `conda env create --name elwah_env --file=environment.yml`
# `conda activate elwah_env`
# `conda env update --file environment.yml --prune`

name: elwah_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pillow
  - matplotlib
  - pip:
    - opencv-python
